# Generated by Django 5.0 on 2024-02-08 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0005_register'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='passsword',
            new_name='password',
        ),
    ]
